name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 mypy
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        # Остановка сборки при наличии ошибок синтаксиса или неопределенных имен
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Остальные ошибки рассматриваются как предупреждения
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics
    - name: Type check with mypy
      run: |
        mypy --ignore-missing-imports --disallow-untyped-defs --disallow-incomplete-defs cmd langs testengines ui 